const BLOCK_TYPE = {
  AIR: 0,
  GRASS_BLOCK: 1,
  DIRT: 2,
  STONE: 3,
  COAL: 4,
  IRON: 5,
  WOOD: 6,
  BEDROCK: 7,
  COBBLESTONE: 8,
  STONE_BRICK: 9,
  TORCH: 10,
  LEAVES: 11,
  GRASS: 12,
  ROSE: 13,
};

const BLOCK_TRANSPARENCY = {};

BLOCK_TRANSPARENCY[BLOCK_TYPE.GRASS_BLOCK] =
  BLOCK_TRANSPARENCY[BLOCK_TYPE.DIRT] =
  BLOCK_TRANSPARENCY[BLOCK_TYPE.STONE] =
  BLOCK_TRANSPARENCY[BLOCK_TYPE.COAL] =
  BLOCK_TRANSPARENCY[BLOCK_TYPE.IRON] =
  BLOCK_TRANSPARENCY[BLOCK_TYPE.WOOD] =
  BLOCK_TRANSPARENCY[BLOCK_TYPE.BEDROCK] =
  BLOCK_TRANSPARENCY[BLOCK_TYPE.COBBLESTONE] =
  BLOCK_TRANSPARENCY[BLOCK_TYPE.STONE_BRICK] = 0;

BLOCK_TRANSPARENCY[BLOCK_TYPE.AIR] =
  BLOCK_TRANSPARENCY[BLOCK_TYPE.TORCH] =
  BLOCK_TRANSPARENCY[BLOCK_TYPE.GRASS] =
  BLOCK_TRANSPARENCY[BLOCK_TYPE.ROSE] =
  1;

BLOCK_TRANSPARENCY[BLOCK_TYPE.LEAVES] =
  2;

const BLOCK_LIGHT = {};

BLOCK_LIGHT[BLOCK_TYPE.TORCH] = 14;

for (const key in BLOCK_TYPE)
  if (Object.hasOwnProperty.call(BLOCK_TYPE, key) && !Object.hasOwnProperty.call(BLOCK_LIGHT, BLOCK_TYPE[key]))
    BLOCK_LIGHT[BLOCK_TYPE[key]] = 0;

export { BLOCK_TYPE, BLOCK_TRANSPARENCY, BLOCK_LIGHT };