const BLOCK_TYPE = {
  AIR: 0,
  GRASS_BLOCK: 1,
  DIRT: 2,
  STONE: 3,
  COAL: 4,
  IRON: 5,
  WOOD: 6,
  BEDROCK: 7,
  COBBLESTONE: 8,
  STONE_BRICK: 9,
  TORCH: 10,
  LEAVES: 11,
  GRASS: 12,
  ROSE: 13,
  SAND: 14,
  SANDSTONE: 15,
  DEAD_BUSH: 16,
  CACTUS: 17,
  WATER: 18,
};

const BLOCK_TRANSPARENCY = {};

BLOCK_TRANSPARENCY[BLOCK_TYPE.AIR] =
  BLOCK_TRANSPARENCY[BLOCK_TYPE.WATER] =
  BLOCK_TRANSPARENCY[BLOCK_TYPE.TORCH] =
  BLOCK_TRANSPARENCY[BLOCK_TYPE.GRASS] =
  BLOCK_TRANSPARENCY[BLOCK_TYPE.ROSE] =
  BLOCK_TRANSPARENCY[BLOCK_TYPE.DEAD_BUSH] =
  1;

BLOCK_TRANSPARENCY[BLOCK_TYPE.LEAVES] =
  BLOCK_TRANSPARENCY[BLOCK_TYPE.CACTUS] =
  2;

const BLOCK_LIGHT = {};

BLOCK_LIGHT[BLOCK_TYPE.TORCH] = 14;

for (const key in BLOCK_TYPE) {
  if (!Object.hasOwnProperty.call(BLOCK_TYPE, key))
    continue;

  if (!Object.hasOwnProperty.call(BLOCK_TRANSPARENCY, BLOCK_TYPE[key]))
    BLOCK_TRANSPARENCY[BLOCK_TYPE[key]] = 0;

  if (!Object.hasOwnProperty.call(BLOCK_LIGHT, BLOCK_TYPE[key]))
    BLOCK_LIGHT[BLOCK_TYPE[key]] = 0;
}

const BLOCK_SOUND = {};

BLOCK_SOUND[BLOCK_TYPE.GRASS_BLOCK] =
  BLOCK_SOUND[BLOCK_TYPE.LEAVES] =
  BLOCK_SOUND[BLOCK_TYPE.GRASS] =
  BLOCK_SOUND[BLOCK_TYPE.DEAD_BUSH] =
  BLOCK_SOUND[BLOCK_TYPE.ROSE] =
  BLOCK_SOUND[BLOCK_TYPE.DIRT] = "grassSong";

BLOCK_SOUND[BLOCK_TYPE.STONE] =
  BLOCK_SOUND[BLOCK_TYPE.IRON] =
  BLOCK_SOUND[BLOCK_TYPE.COBBLESTONE] =
  BLOCK_SOUND[BLOCK_TYPE.STONE_BRICK] =
  BLOCK_SOUND[BLOCK_TYPE.STONE] =
  BLOCK_SOUND[BLOCK_TYPE.SANDSTONE] =
  BLOCK_SOUND[BLOCK_TYPE.COAL] = "stoneSong";

BLOCK_SOUND[BLOCK_TYPE.WOOD] =
  BLOCK_SOUND[BLOCK_TYPE.CACTUS] = "woodSong";

BLOCK_SOUND[BLOCK_TYPE.SAND] = "sandSong";

const SOUND_VOL = {};

SOUND_VOL["grassSong"] = 0.5;
SOUND_VOL["stoneSong"] = 1;
SOUND_VOL["woodSong"] = 0.8;
SOUND_VOL["sandSong"] = 1.3;

export { BLOCK_TYPE, BLOCK_TRANSPARENCY, BLOCK_LIGHT, BLOCK_SOUND,SOUND_VOL };