const CONFIG = {};

CONFIG.CHUNK_SPAWN_DIST = 7;
CONFIG.CHUNK_REMOVE_DIST = CONFIG.CHUNK_SPAWN_DIST + 1;

CONFIG.CHUNK_SIZE = 16;
CONFIG.WORLD_SUB_CHUNKS_HEIGHT = 2;
CONFIG.CHUNK_HEIGHT = CONFIG.CHUNK_SIZE * CONFIG.WORLD_SUB_CHUNKS_HEIGHT;
CONFIG.WORLD_HEIGHT = CONFIG.CHUNK_HEIGHT;
CONFIG.MIN_BLOCK_Y = 0;
CONFIG.MAX_BLOCK_Y = CONFIG.WORLD_HEIGHT - 1;

CONFIG.MAX_LIGHT = 15;

export default CONFIG;